// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7hWX1uHWiNl31kcZE_PcdZplfmiwDrgA',
    appId: '1:76707753417:web:4d69cdaaee9a5cda3a0c18',
    messagingSenderId: '76707753417',
    projectId: 'contractcentral-41c9d',
    authDomain: 'contractcentral-41c9d.firebaseapp.com',
    storageBucket: 'contractcentral-41c9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBxpRyGqJpa2KYoaJJNnERKD-5rdiSU-0',
    appId: '1:76707753417:android:2af4ea5215823a663a0c18',
    messagingSenderId: '76707753417',
    projectId: 'contractcentral-41c9d',
    storageBucket: 'contractcentral-41c9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABjOuzhLPCiHvvFkgB5jz3mjuyy46mbSk',
    appId: '1:76707753417:ios:ee76cceeb78d2bb73a0c18',
    messagingSenderId: '76707753417',
    projectId: 'contractcentral-41c9d',
    storageBucket: 'contractcentral-41c9d.firebasestorage.app',
    iosBundleId: 'com.example.contractCentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABjOuzhLPCiHvvFkgB5jz3mjuyy46mbSk',
    appId: '1:76707753417:ios:ee76cceeb78d2bb73a0c18',
    messagingSenderId: '76707753417',
    projectId: 'contractcentral-41c9d',
    storageBucket: 'contractcentral-41c9d.firebasestorage.app',
    iosBundleId: 'com.example.contractCentral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7hWX1uHWiNl31kcZE_PcdZplfmiwDrgA',
    appId: '1:76707753417:web:6d35e2dab1e776273a0c18',
    messagingSenderId: '76707753417',
    projectId: 'contractcentral-41c9d',
    authDomain: 'contractcentral-41c9d.firebaseapp.com',
    storageBucket: 'contractcentral-41c9d.firebasestorage.app',
  );
}
